springdoc:
  swagger-ui:
    path: /
    urls-primary-name: teste


enviroments:
  project-version: @project.version@
  project-name: @project.name@
  project-description: @project.description@
  any-name: any value here
  any-name-enviroment: ${JAVA-HOME}

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2